//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: dds_cdrBlob.h
//  Source: /home/dds/OvernightTests/ExtraToday/opensplice-test/tags/OSPL_V6_9_181127OSS_RELEASE/rhel72a/x86_64.linux-release/build/etc/idl/dds_cdrBlob.idl
//  Generated: Wed Nov 28 07:49:47 2018
//  OpenSplice 6.9.181127OSS
//  
//******************************************************************
#ifndef _DDS_CDRBLOB_H_
#define _DDS_CDRBLOB_H_

#include "sacpp_mapping.h"


namespace DDS
{
   struct CDRSample;
   struct CDRBlob_uniq_ {};
   typedef DDS_DCPSUFLSeq < Octet, struct CDRBlob_uniq_> CDRBlob;
   typedef DDS_DCPSSequence_var < CDRBlob> CDRBlob_var;
   typedef DDS_DCPSSequence_out < CDRBlob> CDRBlob_out;

   struct CDRSample
   {
         CDRBlob blob;
   };

   typedef DDS_DCPSStruct_var < CDRSample> CDRSample_var;
   typedef DDS_DCPSStruct_out < CDRSample> CDRSample_out;
}




#endif
