//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: dds_cdrBlob.h
//  Source: /mnt/h/home/rfactory/opensplice-master/etc/idl/dds_cdrBlob.idl
//  Generated: Fri Mar 15 14:33:57 2019
//  OpenSplice 6.9.190227OSS
//  
//******************************************************************
#ifndef _DDS_CDRBLOB_H_
#define _DDS_CDRBLOB_H_

#include "sacpp_mapping.h"


namespace DDS
{
   struct CDRSample;
   struct CDRBlob_uniq_ {};
   typedef DDS_DCPSUFLSeq < Octet, struct CDRBlob_uniq_> CDRBlob;
   typedef DDS_DCPSSequence_var < CDRBlob> CDRBlob_var;
   typedef DDS_DCPSSequence_out < CDRBlob> CDRBlob_out;

   struct CDRSample
   {
         CDRBlob blob;
   };

   typedef DDS_DCPSStruct_var < CDRSample> CDRSample_var;
   typedef DDS_DCPSStruct_out < CDRSample> CDRSample_out;
}




#endif
