//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: dds_namedQosTypesDcps.h
//  Source: dds_namedQosTypesDcps.idl
//  Generated: Wed Mar 19 10:58:06 2014
//  OpenSplice V6.4.140320OSS
//  
//******************************************************************
#ifndef _DDS_NAMEDQOSTYPESDCPS_H_
#define _DDS_NAMEDQOSTYPESDCPS_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"
#include "dds_dcps_builtintopics.h"
#include "dds_dcps.h"
#include "dds_namedQosTypes.h"






#endif 
