#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------
JAVAC         = $(SPLICE_JAVAC)
JAR           = jar
JAVACFLAGS    = $(GENFLAGS) -sourcepath ../src
CLASSEXT      = .class
CLASSDIR      = classes/
OUTPUT_OPTION = -d $(CLASSDIR)
COMPILE.java  = $(JAVAC) $(JAVACFLAGS) -cp $(JAVACCPATH) 
JAVACCPATH    = "$(SPLICE_EXTRA_CP):saj5_tutorial_types.jar:$(CLASSDIR):../../../../jar/dcpssaj5.jar:"
MAKEFILE      = Makefile.saj5_tutorial_chatter
DEPENDENCIES  = $(MAKEFILE)
LTARGETDIR    = ./
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
GENFLAGS      =  
CLASSES       =  $(CLASSDIR)chatroom/Chatter$(CLASSEXT)
JARCLASSES    =  chatroom/Chatter$(CLASSEXT)
JAREXT        = .jar
MAINCLASS     = chatroom.Chatter
JARFILE       = $(LTARGETDIR)$(LIBPREFIX)saj5_tutorial_chatter$(LIBSUFFIX)$(JAREXT)
MANIFEST      = saj5_tutorial_chatter.manifest
JARFLAGS      = cvfm
SRC           = src/chatroom/Chatter.java

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(JARFILE)

$(JARFILE): $(CLASSES) $(CLASSDIR)$(MANIFEST)
	@$(TESTDIRSTART) "$(LTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(LTARGETDIR)"
	cd $(CLASSDIR) && $(JAR) $(JARFLAGS) $(JARFILE) $(MANIFEST) $(JARCLASSES) 
	$(MV) $(CLASSDIR)/$(JARFILE) .

$(CLASSDIR)$(MANIFEST):
	echo Class-Path: saj5_tutorial_types.jar ../../../../jar/dcpssaj5.jar > $(CLASSDIR)$(MANIFEST)
	echo Main-Class: $(MAINCLASS) >> $(CLASSDIR)$(MANIFEST)

generated: $(GENERATED_DIRTY)
	@-:

$(CLASSDIR)chatroom/Chatter$(CLASSEXT): src/chatroom/Chatter.java
	@$(TESTDIRSTART) "$(CLASSDIR)chatroom/" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)chatroom/"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) src/chatroom/Chatter.java

clean:
	-$(RM) $(CLASSES)

realclean: clean
	-$(RM) $(BIN)
	-$(RM) $(CLASSDIR)$(MANIFEST)
	-$(RM) chatroom/

check-syntax:
	$(COMPILE.java) $(EXPORTFLAGS) $(CHK_SOURCES)

