//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ishape.cpp
//  Source: ishape.idl
//  Generated: Fri Jul 28 15:34:45 2017
//  OpenSplice V6.4.140320OSS
//  
//******************************************************************

#include "ishape.h"




