#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------
JAVAC         = $(SPLICE_JAVAC)
JAR           = jar
JAVACFLAGS    = $(GENFLAGS)
CLASSEXT      = .class
CLASSDIR      = classes/
OUTPUT_OPTION = -d $(CLASSDIR)
COMPILE.java  = $(JAVAC) $(JAVACFLAGS) -cp $(JAVACCPATH) 
JAVACCPATH    = "$(SPLICE_EXTRA_CP):$(CLASSDIR):../../../../jar/dcpssaj5.jar:../../../../jar/ddsface.jar:"
MAKEFILE      = Makefile.face_helloworld_types
DEPENDENCIES  = $(MAKEFILE)
LTARGETDIR    = ./
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
GENFLAGS      =  
CLASSES       =  $(CLASSDIR)HelloWorldData/*$(CLASSEXT) $(CLASSDIR)HelloWorldDataPublisher$(CLASSEXT) $(CLASSDIR)HelloWorldDataSubscriber$(CLASSEXT)
JARCLASSES    =  HelloWorldData/*$(CLASSEXT) HelloWorldDataPublisher$(CLASSEXT) HelloWorldDataSubscriber$(CLASSEXT)
JAREXT        = .jar
MAINCLASS     = HelloWorldDataPublisher
JARFILE       = $(LTARGETDIR)$(LIBPREFIX)face_helloworld_types$(LIBSUFFIX)$(JAREXT)
MANIFEST      = face_helloworld_types.manifest
JARFLAGS      = cvfm
SRC           = HelloWorldData/*.java HelloWorldDataPublisher.java HelloWorldDataSubscriber.java

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(JARFILE)

$(JARFILE): $(CLASSES) $(CLASSDIR)$(MANIFEST)
	@$(TESTDIRSTART) "$(LTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(LTARGETDIR)"
	cd $(CLASSDIR) && $(JAR) $(JARFLAGS) $(JARFILE) $(MANIFEST) $(JARCLASSES) 
	$(MV) $(CLASSDIR)/$(JARFILE) .

$(CLASSDIR)$(MANIFEST):
	echo Class-Path: ../../../../jar/dcpssaj5.jar ../../../../jar/ddsface.jar > $(CLASSDIR)$(MANIFEST)
	echo Main-Class: $(MAINCLASS) >> $(CLASSDIR)$(MANIFEST)

GENERATED_DIRTY = HelloWorldData

HelloWorldData: ../idl/HelloWorldData.idl
	"../../../../bin/idlpp" -I "../../../../etc/idl" -l java -F ../idl/HelloWorldData.idl

.PRECIOUS: $(GENERATED_DIRTY)
$(CLASSES): $(GENERATED_DIRTY)

generated: $(GENERATED_DIRTY)
	@-:

$(CLASSDIR)HelloWorldData/*$(CLASSEXT): HelloWorldData
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) HelloWorldData/*.java

$(CLASSDIR)HelloWorldDataPublisher$(CLASSEXT): HelloWorldDataPublisher.java
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) HelloWorldDataPublisher.java

$(CLASSDIR)HelloWorldDataSubscriber$(CLASSEXT): HelloWorldDataSubscriber.java
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) HelloWorldDataSubscriber.java

clean:
	-$(RM) $(CLASSES)

realclean: clean
	-$(RM) $(BIN)
	-$(RM) $(GENERATED_DIRTY)
	-$(RM) $(CLASSDIR)$(MANIFEST)

check-syntax:
	$(COMPILE.java) $(EXPORTFLAGS) $(CHK_SOURCES)

