// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.1.1
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:461

#ifndef _TAO_IDL_DDS_DCPS_BUILTINTOPICSS_BTCGON_H_
#define _TAO_IDL_DDS_DCPS_BUILTINTOPICSS_BTCGON_H_


#include "dds_dcps_builtintopicsC.h"
#include "dds_builtinTopicsS.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/Fixed_Size_SArgument_T.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"
#include "tao/PortableServer/UB_String_SArguments.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::Time_t>
    : public
        Fixed_Size_SArg_Traits_T<
            ::DDS::Time_t,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::EntityFactoryQosPolicy>
    : public
        Fixed_Size_SArg_Traits_T<
            ::DDS::EntityFactoryQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::WriterDataLifecycleQosPolicy>
    : public
        Fixed_Size_SArg_Traits_T<
            ::DDS::WriterDataLifecycleQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:898

  template<>
  class SArg_Traits< ::DDS::InvalidSampleVisibilityQosPolicyKind>
    : public
        Basic_SArg_Traits_T<
            ::DDS::InvalidSampleVisibilityQosPolicyKind,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::InvalidSampleVisibilityQosPolicy>
    : public
        Fixed_Size_SArg_Traits_T<
            ::DDS::InvalidSampleVisibilityQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::ReaderDataLifecycleQosPolicy>
    : public
        Fixed_Size_SArg_Traits_T<
            ::DDS::ReaderDataLifecycleQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::SubscriptionKeyQosPolicy>
    : public
        Var_Size_SArg_Traits_T<
            ::DDS::SubscriptionKeyQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::ReaderLifespanQosPolicy>
    : public
        Fixed_Size_SArg_Traits_T<
            ::DDS::ReaderLifespanQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::ShareQosPolicy>
    : public
        Var_Size_SArg_Traits_T<
            ::DDS::ShareQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:898

  template<>
  class SArg_Traits< ::DDS::SchedulingClassQosPolicyKind>
    : public
        Basic_SArg_Traits_T<
            ::DDS::SchedulingClassQosPolicyKind,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::SchedulingClassQosPolicy>
    : public
        Fixed_Size_SArg_Traits_T<
            ::DDS::SchedulingClassQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:898

  template<>
  class SArg_Traits< ::DDS::SchedulingPriorityQosPolicyKind>
    : public
        Basic_SArg_Traits_T<
            ::DDS::SchedulingPriorityQosPolicyKind,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::SchedulingPriorityQosPolicy>
    : public
        Fixed_Size_SArg_Traits_T<
            ::DDS::SchedulingPriorityQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::SchedulingQosPolicy>
    : public
        Fixed_Size_SArg_Traits_T<
            ::DDS::SchedulingQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::ViewKeyQosPolicy>
    : public
        Var_Size_SArg_Traits_T<
            ::DDS::ViewKeyQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::DataReaderViewQos>
    : public
        Var_Size_SArg_Traits_T<
            ::DDS::DataReaderViewQos,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::DomainParticipantFactoryQos>
    : public
        Fixed_Size_SArg_Traits_T<
            ::DDS::DomainParticipantFactoryQos,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::DomainParticipantQos>
    : public
        Var_Size_SArg_Traits_T<
            ::DDS::DomainParticipantQos,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::TopicQos>
    : public
        Var_Size_SArg_Traits_T<
            ::DDS::TopicQos,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::DataWriterQos>
    : public
        Var_Size_SArg_Traits_T<
            ::DDS::DataWriterQos,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::PublisherQos>
    : public
        Var_Size_SArg_Traits_T<
            ::DDS::PublisherQos,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::DataReaderQos>
    : public
        Var_Size_SArg_Traits_T<
            ::DDS::DataReaderQos,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::SubscriberQos>
    : public
        Var_Size_SArg_Traits_T<
            ::DDS::SubscriberQos,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:38

namespace POA_DDS
{
  

// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:69

} // module DDS

#endif /* ifndef */

