// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.1.1
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:461

#ifndef _TAO_IDL_DDS_DCPS_INTERFACESS_BQNMZ8_H_
#define _TAO_IDL_DDS_DCPS_INTERFACESS_BQNMZ8_H_


#include "dds_dcps_interfacesC.h"
#include "dds_dcps_builtintopicsS.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/Fixed_Size_SArgument_T.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"
#include "tao/PortableServer/UB_String_SArguments.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:679

  template<>
  class SArg_Traits< ::DDS::InstanceHandleSeq>
    : public
        Var_Size_SArg_Traits_T<
            ::DDS::InstanceHandleSeq,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::InconsistentTopicStatus>
    : public
        Fixed_Size_SArg_Traits_T<
            ::DDS::InconsistentTopicStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::AllDataDisposedTopicStatus>
    : public
        Fixed_Size_SArg_Traits_T<
            ::DDS::AllDataDisposedTopicStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::SampleLostStatus>
    : public
        Fixed_Size_SArg_Traits_T<
            ::DDS::SampleLostStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:898

  template<>
  class SArg_Traits< ::DDS::SampleRejectedStatusKind>
    : public
        Basic_SArg_Traits_T<
            ::DDS::SampleRejectedStatusKind,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::SampleRejectedStatus>
    : public
        Fixed_Size_SArg_Traits_T<
            ::DDS::SampleRejectedStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::LivelinessLostStatus>
    : public
        Fixed_Size_SArg_Traits_T<
            ::DDS::LivelinessLostStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::LivelinessChangedStatus>
    : public
        Fixed_Size_SArg_Traits_T<
            ::DDS::LivelinessChangedStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::OfferedDeadlineMissedStatus>
    : public
        Fixed_Size_SArg_Traits_T<
            ::DDS::OfferedDeadlineMissedStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::RequestedDeadlineMissedStatus>
    : public
        Fixed_Size_SArg_Traits_T<
            ::DDS::RequestedDeadlineMissedStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::QosPolicyCount>
    : public
        Fixed_Size_SArg_Traits_T<
            ::DDS::QosPolicyCount,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:679

  template<>
  class SArg_Traits< ::DDS::QosPolicyCountSeq>
    : public
        Var_Size_SArg_Traits_T<
            ::DDS::QosPolicyCountSeq,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::OfferedIncompatibleQosStatus>
    : public
        Var_Size_SArg_Traits_T<
            ::DDS::OfferedIncompatibleQosStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::RequestedIncompatibleQosStatus>
    : public
        Var_Size_SArg_Traits_T<
            ::DDS::RequestedIncompatibleQosStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::PublicationMatchedStatus>
    : public
        Fixed_Size_SArg_Traits_T<
            ::DDS::PublicationMatchedStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::SubscriptionMatchedStatus>
    : public
        Fixed_Size_SArg_Traits_T<
            ::DDS::SubscriptionMatchedStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:679

  template<>
  class SArg_Traits< ::DDS::TopicSeq>
    : public
        Var_Size_SArg_Traits_T<
            ::DDS::TopicSeq,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:679

  template<>
  class SArg_Traits< ::DDS::DataReaderSeq>
    : public
        Var_Size_SArg_Traits_T<
            ::DDS::DataReaderSeq,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:679

  template<>
  class SArg_Traits< ::DDS::ConditionSeq>
    : public
        Var_Size_SArg_Traits_T<
            ::DDS::ConditionSeq,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:679

  template<>
  class SArg_Traits< ::DDS::SampleStateSeq>
    : public
        Var_Size_SArg_Traits_T<
            ::DDS::SampleStateSeq,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:679

  template<>
  class SArg_Traits< ::DDS::ViewStateSeq>
    : public
        Var_Size_SArg_Traits_T<
            ::DDS::ViewStateSeq,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:679

  template<>
  class SArg_Traits< ::DDS::InstanceStateSeq>
    : public
        Var_Size_SArg_Traits_T<
            ::DDS::InstanceStateSeq,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::Property>
    : public
        Var_Size_SArg_Traits_T<
            ::DDS::Property,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::DDS::SampleInfo>
    : public
        Fixed_Size_SArg_Traits_T<
            ::DDS::SampleInfo,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:679

  template<>
  class SArg_Traits< ::DDS::SampleInfoSeq>
    : public
        Var_Size_SArg_Traits_T<
            ::DDS::SampleInfoSeq,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:38

namespace POA_DDS
{
  

// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:69

} // module DDS

#endif /* ifndef */

