// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.1.1
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL_DDS_NAMEDQOSTYPESC_OIWBQS_H_
#define _TAO_IDL_DDS_NAMEDQOSTYPESC_OIWBQS_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/Basic_Types.h"
#include "tao/String_Manager_T.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "dds_dcps_builtintopicsC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 1 || TAO_BETA_VERSION != 1
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace DDS
{

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct NamedDomainParticipantQos;

  typedef
    ::TAO_Var_Var_T<
        NamedDomainParticipantQos
      >
    NamedDomainParticipantQos_var;

  typedef
    ::TAO_Out_T<
        NamedDomainParticipantQos
      >
    NamedDomainParticipantQos_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  NamedDomainParticipantQos
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef NamedDomainParticipantQos_var _var_type;
    typedef NamedDomainParticipantQos_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager name;
    DDS::DomainParticipantQos domainparticipant_qos;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_NamedDomainParticipantQos;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct NamedPublisherQos;

  typedef
    ::TAO_Var_Var_T<
        NamedPublisherQos
      >
    NamedPublisherQos_var;

  typedef
    ::TAO_Out_T<
        NamedPublisherQos
      >
    NamedPublisherQos_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  NamedPublisherQos
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef NamedPublisherQos_var _var_type;
    typedef NamedPublisherQos_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager name;
    DDS::PublisherQos publisher_qos;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_NamedPublisherQos;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct NamedSubscriberQos;

  typedef
    ::TAO_Var_Var_T<
        NamedSubscriberQos
      >
    NamedSubscriberQos_var;

  typedef
    ::TAO_Out_T<
        NamedSubscriberQos
      >
    NamedSubscriberQos_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  NamedSubscriberQos
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef NamedSubscriberQos_var _var_type;
    typedef NamedSubscriberQos_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager name;
    DDS::SubscriberQos subscriber_qos;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_NamedSubscriberQos;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct NamedTopicQos;

  typedef
    ::TAO_Var_Var_T<
        NamedTopicQos
      >
    NamedTopicQos_var;

  typedef
    ::TAO_Out_T<
        NamedTopicQos
      >
    NamedTopicQos_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  NamedTopicQos
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef NamedTopicQos_var _var_type;
    typedef NamedTopicQos_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager name;
    DDS::TopicQos topic_qos;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_NamedTopicQos;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct NamedDataWriterQos;

  typedef
    ::TAO_Var_Var_T<
        NamedDataWriterQos
      >
    NamedDataWriterQos_var;

  typedef
    ::TAO_Out_T<
        NamedDataWriterQos
      >
    NamedDataWriterQos_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  NamedDataWriterQos
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef NamedDataWriterQos_var _var_type;
    typedef NamedDataWriterQos_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager name;
    DDS::DataWriterQos datawriter_qos;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_NamedDataWriterQos;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct NamedDataReaderQos;

  typedef
    ::TAO_Var_Var_T<
        NamedDataReaderQos
      >
    NamedDataReaderQos_var;

  typedef
    ::TAO_Out_T<
        NamedDataReaderQos
      >
    NamedDataReaderQos_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  NamedDataReaderQos
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef NamedDataReaderQos_var _var_type;
    typedef NamedDataReaderQos_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager name;
    DDS::DataReaderQos datareader_qos;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_NamedDataReaderQos;

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module DDS

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::NamedDomainParticipantQos>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::NamedDomainParticipantQos,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::NamedPublisherQos>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::NamedPublisherQos,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::NamedSubscriberQos>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::NamedSubscriberQos,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::NamedTopicQos>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::NamedTopicQos,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::NamedDataWriterQos>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::NamedDataWriterQos,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::NamedDataReaderQos>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::NamedDataReaderQos,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::NamedDomainParticipantQos &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::NamedDomainParticipantQos*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::NamedDomainParticipantQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::NamedDomainParticipantQos *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::NamedDomainParticipantQos &); // copying version
 void operator<<= (::CORBA::Any &, DDS::NamedDomainParticipantQos*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::NamedDomainParticipantQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::NamedDomainParticipantQos *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::NamedPublisherQos &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::NamedPublisherQos*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::NamedPublisherQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::NamedPublisherQos *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::NamedPublisherQos &); // copying version
 void operator<<= (::CORBA::Any &, DDS::NamedPublisherQos*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::NamedPublisherQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::NamedPublisherQos *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::NamedSubscriberQos &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::NamedSubscriberQos*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::NamedSubscriberQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::NamedSubscriberQos *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::NamedSubscriberQos &); // copying version
 void operator<<= (::CORBA::Any &, DDS::NamedSubscriberQos*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::NamedSubscriberQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::NamedSubscriberQos *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::NamedTopicQos &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::NamedTopicQos*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::NamedTopicQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::NamedTopicQos *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::NamedTopicQos &); // copying version
 void operator<<= (::CORBA::Any &, DDS::NamedTopicQos*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::NamedTopicQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::NamedTopicQos *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::NamedDataWriterQos &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::NamedDataWriterQos*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::NamedDataWriterQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::NamedDataWriterQos *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::NamedDataWriterQos &); // copying version
 void operator<<= (::CORBA::Any &, DDS::NamedDataWriterQos*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::NamedDataWriterQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::NamedDataWriterQos *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::NamedDataReaderQos &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::NamedDataReaderQos*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::NamedDataReaderQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::NamedDataReaderQos *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::NamedDataReaderQos &); // copying version
 void operator<<= (::CORBA::Any &, DDS::NamedDataReaderQos*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::NamedDataReaderQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::NamedDataReaderQos *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::NamedDomainParticipantQos &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::NamedDomainParticipantQos &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::NamedPublisherQos &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::NamedPublisherQos &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::NamedSubscriberQos &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::NamedSubscriberQos &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::NamedTopicQos &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::NamedTopicQos &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::NamedDataWriterQos &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::NamedDataWriterQos &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::NamedDataReaderQos &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::NamedDataReaderQos &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "dds_namedQosTypesC.inl"
#endif /* defined INLINE */

#endif /* ifndef */

