// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.1.1
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL_DDS_BUILTINTOPICSC_EMQEFA_H_
#define _TAO_IDL_DDS_BUILTINTOPICSC_EMQEFA_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/Basic_Types.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/VarOut_T.h"
#include "tao/Array_VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Basic_Argument_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include "tao/Fixed_Array_Argument_T.h"
#include "tao/Var_Array_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 1 || TAO_BETA_VERSION != 1
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace DDS
{

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_DDS_OCTSEQ_CH_)
#define _DDS_OCTSEQ_CH_

  class octSeq;

  typedef
    ::TAO_FixedSeq_Var_T<
        octSeq
      >
    octSeq_var;

  typedef
    ::TAO_Seq_Out_T<
        octSeq
      >
    octSeq_out;

  class  octSeq
    : public
        ::TAO::unbounded_value_sequence<
            ::CORBA::Octet
          >
  {
  public:
    octSeq (void);
    octSeq ( ::CORBA::ULong max);
    octSeq (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ::CORBA::Octet* buffer,
      ::CORBA::Boolean release = false);
    octSeq (const octSeq &);
    virtual ~octSeq (void);
    

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef octSeq_var _var_type;
    typedef octSeq_out _out_type;

    static void _tao_any_destructor (void *);

    

#if (TAO_NO_COPY_OCTET_SEQUENCES == 1)
    octSeq (
        ::CORBA::ULong length,
        const ACE_Message_Block* mb
      )
      : ::TAO::unbounded_value_sequence< ::CORBA::Octet> (length, mb) {}
#endif /* TAO_NO_COPY_OCTET_SEQUENCE == 1 */
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_octSeq;

  // TAO_IDL - Generated from
  // be/be_visitor_array/array_ch.cpp:54

  typedef ::CORBA::Long BuiltinTopicKey_t[3];
  typedef ::CORBA::Long BuiltinTopicKey_t_slice;
  struct BuiltinTopicKey_t_tag {};
  

  typedef
    TAO_FixedArray_Var_T<
        BuiltinTopicKey_t,
        BuiltinTopicKey_t_slice,
        BuiltinTopicKey_t_tag
      >
    BuiltinTopicKey_t_var;

  typedef
    BuiltinTopicKey_t
    BuiltinTopicKey_t_out;

  typedef
    TAO_Array_Forany_T<
        BuiltinTopicKey_t,
        BuiltinTopicKey_t_slice,
        BuiltinTopicKey_t_tag
      >
    BuiltinTopicKey_t_forany;

  TAO_NAMESPACE_STORAGE_CLASS BuiltinTopicKey_t_slice *
  BuiltinTopicKey_t_alloc (void);

  TAO_NAMESPACE_STORAGE_CLASS void
  BuiltinTopicKey_t_free (
      BuiltinTopicKey_t_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS BuiltinTopicKey_t_slice *
  BuiltinTopicKey_t_dup (
      const BuiltinTopicKey_t_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS void
  BuiltinTopicKey_t_copy (
      BuiltinTopicKey_t_slice *_tao_to,
      const BuiltinTopicKey_t_slice *_tao_from);

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_BuiltinTopicKey_t;

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_DDS_STRINGSEQ_CH_)
#define _DDS_STRINGSEQ_CH_

  class StringSeq;

  typedef
    ::TAO_VarSeq_Var_T<
        StringSeq
      >
    StringSeq_var;

  typedef
    ::TAO_Seq_Out_T<
        StringSeq
      >
    StringSeq_out;

  class  StringSeq
    : public
        ::TAO::unbounded_basic_string_sequence<char>
  {
  public:
    StringSeq (void);
    StringSeq ( ::CORBA::ULong max);
    StringSeq (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ::CORBA::Char ** buffer,
      ::CORBA::Boolean release = false);
    StringSeq (const StringSeq &);
    virtual ~StringSeq (void);
    

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef StringSeq_var _var_type;
    typedef StringSeq_out _out_type;

    static void _tao_any_destructor (void *);
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_StringSeq;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct Duration_t;

  typedef
    ::TAO_Fixed_Var_T<
        Duration_t
      >
    Duration_t_var;

  typedef
    Duration_t &
    Duration_t_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  Duration_t
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef Duration_t_var _var_type;
    typedef Duration_t_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::CORBA::Long sec;
    ::CORBA::ULong nanosec;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_Duration_t;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct UserDataQosPolicy;

  typedef
    ::TAO_Var_Var_T<
        UserDataQosPolicy
      >
    UserDataQosPolicy_var;

  typedef
    ::TAO_Out_T<
        UserDataQosPolicy
      >
    UserDataQosPolicy_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  UserDataQosPolicy
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef UserDataQosPolicy_var _var_type;
    typedef UserDataQosPolicy_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::octSeq value;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_UserDataQosPolicy;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct TopicDataQosPolicy;

  typedef
    ::TAO_Var_Var_T<
        TopicDataQosPolicy
      >
    TopicDataQosPolicy_var;

  typedef
    ::TAO_Out_T<
        TopicDataQosPolicy
      >
    TopicDataQosPolicy_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  TopicDataQosPolicy
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef TopicDataQosPolicy_var _var_type;
    typedef TopicDataQosPolicy_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::octSeq value;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_TopicDataQosPolicy;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct GroupDataQosPolicy;

  typedef
    ::TAO_Var_Var_T<
        GroupDataQosPolicy
      >
    GroupDataQosPolicy_var;

  typedef
    ::TAO_Out_T<
        GroupDataQosPolicy
      >
    GroupDataQosPolicy_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  GroupDataQosPolicy
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef GroupDataQosPolicy_var _var_type;
    typedef GroupDataQosPolicy_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::octSeq value;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_GroupDataQosPolicy;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct TransportPriorityQosPolicy;

  typedef
    ::TAO_Fixed_Var_T<
        TransportPriorityQosPolicy
      >
    TransportPriorityQosPolicy_var;

  typedef
    TransportPriorityQosPolicy &
    TransportPriorityQosPolicy_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  TransportPriorityQosPolicy
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef TransportPriorityQosPolicy_var _var_type;
    typedef TransportPriorityQosPolicy_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::CORBA::Long value;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_TransportPriorityQosPolicy;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct LifespanQosPolicy;

  typedef
    ::TAO_Fixed_Var_T<
        LifespanQosPolicy
      >
    LifespanQosPolicy_var;

  typedef
    LifespanQosPolicy &
    LifespanQosPolicy_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  LifespanQosPolicy
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef LifespanQosPolicy_var _var_type;
    typedef LifespanQosPolicy_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::Duration_t duration;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_LifespanQosPolicy;

  // TAO_IDL - Generated from
  // be/be_visitor_enum/enum_ch.cpp:47

  enum DurabilityQosPolicyKind
  {
    VOLATILE_DURABILITY_QOS,
    TRANSIENT_LOCAL_DURABILITY_QOS,
    TRANSIENT_DURABILITY_QOS,
    PERSISTENT_DURABILITY_QOS
  };

  typedef DurabilityQosPolicyKind &DurabilityQosPolicyKind_out;

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_DurabilityQosPolicyKind;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct DurabilityQosPolicy;

  typedef
    ::TAO_Fixed_Var_T<
        DurabilityQosPolicy
      >
    DurabilityQosPolicy_var;

  typedef
    DurabilityQosPolicy &
    DurabilityQosPolicy_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  DurabilityQosPolicy
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef DurabilityQosPolicy_var _var_type;
    typedef DurabilityQosPolicy_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::DurabilityQosPolicyKind kind;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_DurabilityQosPolicy;

  // TAO_IDL - Generated from
  // be/be_visitor_enum/enum_ch.cpp:47

  enum PresentationQosPolicyAccessScopeKind
  {
    INSTANCE_PRESENTATION_QOS,
    TOPIC_PRESENTATION_QOS,
    GROUP_PRESENTATION_QOS
  };

  typedef PresentationQosPolicyAccessScopeKind &PresentationQosPolicyAccessScopeKind_out;

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_PresentationQosPolicyAccessScopeKind;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct PresentationQosPolicy;

  typedef
    ::TAO_Fixed_Var_T<
        PresentationQosPolicy
      >
    PresentationQosPolicy_var;

  typedef
    PresentationQosPolicy &
    PresentationQosPolicy_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  PresentationQosPolicy
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef PresentationQosPolicy_var _var_type;
    typedef PresentationQosPolicy_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::PresentationQosPolicyAccessScopeKind access_scope;
    ::CORBA::Boolean coherent_access;
    ::CORBA::Boolean ordered_access;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_PresentationQosPolicy;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct DeadlineQosPolicy;

  typedef
    ::TAO_Fixed_Var_T<
        DeadlineQosPolicy
      >
    DeadlineQosPolicy_var;

  typedef
    DeadlineQosPolicy &
    DeadlineQosPolicy_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  DeadlineQosPolicy
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef DeadlineQosPolicy_var _var_type;
    typedef DeadlineQosPolicy_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::Duration_t period;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_DeadlineQosPolicy;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct LatencyBudgetQosPolicy;

  typedef
    ::TAO_Fixed_Var_T<
        LatencyBudgetQosPolicy
      >
    LatencyBudgetQosPolicy_var;

  typedef
    LatencyBudgetQosPolicy &
    LatencyBudgetQosPolicy_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  LatencyBudgetQosPolicy
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef LatencyBudgetQosPolicy_var _var_type;
    typedef LatencyBudgetQosPolicy_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::Duration_t duration;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_LatencyBudgetQosPolicy;

  // TAO_IDL - Generated from
  // be/be_visitor_enum/enum_ch.cpp:47

  enum OwnershipQosPolicyKind
  {
    SHARED_OWNERSHIP_QOS,
    EXCLUSIVE_OWNERSHIP_QOS
  };

  typedef OwnershipQosPolicyKind &OwnershipQosPolicyKind_out;

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_OwnershipQosPolicyKind;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct OwnershipQosPolicy;

  typedef
    ::TAO_Fixed_Var_T<
        OwnershipQosPolicy
      >
    OwnershipQosPolicy_var;

  typedef
    OwnershipQosPolicy &
    OwnershipQosPolicy_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  OwnershipQosPolicy
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef OwnershipQosPolicy_var _var_type;
    typedef OwnershipQosPolicy_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::OwnershipQosPolicyKind kind;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_OwnershipQosPolicy;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct OwnershipStrengthQosPolicy;

  typedef
    ::TAO_Fixed_Var_T<
        OwnershipStrengthQosPolicy
      >
    OwnershipStrengthQosPolicy_var;

  typedef
    OwnershipStrengthQosPolicy &
    OwnershipStrengthQosPolicy_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  OwnershipStrengthQosPolicy
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef OwnershipStrengthQosPolicy_var _var_type;
    typedef OwnershipStrengthQosPolicy_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::CORBA::Long value;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_OwnershipStrengthQosPolicy;

  // TAO_IDL - Generated from
  // be/be_visitor_enum/enum_ch.cpp:47

  enum LivelinessQosPolicyKind
  {
    AUTOMATIC_LIVELINESS_QOS,
    MANUAL_BY_PARTICIPANT_LIVELINESS_QOS,
    MANUAL_BY_TOPIC_LIVELINESS_QOS
  };

  typedef LivelinessQosPolicyKind &LivelinessQosPolicyKind_out;

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_LivelinessQosPolicyKind;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct LivelinessQosPolicy;

  typedef
    ::TAO_Fixed_Var_T<
        LivelinessQosPolicy
      >
    LivelinessQosPolicy_var;

  typedef
    LivelinessQosPolicy &
    LivelinessQosPolicy_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  LivelinessQosPolicy
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef LivelinessQosPolicy_var _var_type;
    typedef LivelinessQosPolicy_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::LivelinessQosPolicyKind kind;
    DDS::Duration_t lease_duration;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_LivelinessQosPolicy;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct TimeBasedFilterQosPolicy;

  typedef
    ::TAO_Fixed_Var_T<
        TimeBasedFilterQosPolicy
      >
    TimeBasedFilterQosPolicy_var;

  typedef
    TimeBasedFilterQosPolicy &
    TimeBasedFilterQosPolicy_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  TimeBasedFilterQosPolicy
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef TimeBasedFilterQosPolicy_var _var_type;
    typedef TimeBasedFilterQosPolicy_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::Duration_t minimum_separation;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_TimeBasedFilterQosPolicy;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct PartitionQosPolicy;

  typedef
    ::TAO_Var_Var_T<
        PartitionQosPolicy
      >
    PartitionQosPolicy_var;

  typedef
    ::TAO_Out_T<
        PartitionQosPolicy
      >
    PartitionQosPolicy_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  PartitionQosPolicy
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef PartitionQosPolicy_var _var_type;
    typedef PartitionQosPolicy_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::StringSeq name;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_PartitionQosPolicy;

  // TAO_IDL - Generated from
  // be/be_visitor_enum/enum_ch.cpp:47

  enum ReliabilityQosPolicyKind
  {
    BEST_EFFORT_RELIABILITY_QOS,
    RELIABLE_RELIABILITY_QOS
  };

  typedef ReliabilityQosPolicyKind &ReliabilityQosPolicyKind_out;

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_ReliabilityQosPolicyKind;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct ReliabilityQosPolicy;

  typedef
    ::TAO_Fixed_Var_T<
        ReliabilityQosPolicy
      >
    ReliabilityQosPolicy_var;

  typedef
    ReliabilityQosPolicy &
    ReliabilityQosPolicy_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  ReliabilityQosPolicy
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef ReliabilityQosPolicy_var _var_type;
    typedef ReliabilityQosPolicy_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::ReliabilityQosPolicyKind kind;
    DDS::Duration_t max_blocking_time;
    ::CORBA::Boolean synchronous;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_ReliabilityQosPolicy;

  // TAO_IDL - Generated from
  // be/be_visitor_enum/enum_ch.cpp:47

  enum DestinationOrderQosPolicyKind
  {
    BY_RECEPTION_TIMESTAMP_DESTINATIONORDER_QOS,
    BY_SOURCE_TIMESTAMP_DESTINATIONORDER_QOS
  };

  typedef DestinationOrderQosPolicyKind &DestinationOrderQosPolicyKind_out;

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_DestinationOrderQosPolicyKind;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct DestinationOrderQosPolicy;

  typedef
    ::TAO_Fixed_Var_T<
        DestinationOrderQosPolicy
      >
    DestinationOrderQosPolicy_var;

  typedef
    DestinationOrderQosPolicy &
    DestinationOrderQosPolicy_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  DestinationOrderQosPolicy
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef DestinationOrderQosPolicy_var _var_type;
    typedef DestinationOrderQosPolicy_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::DestinationOrderQosPolicyKind kind;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_DestinationOrderQosPolicy;

  // TAO_IDL - Generated from
  // be/be_visitor_enum/enum_ch.cpp:47

  enum HistoryQosPolicyKind
  {
    KEEP_LAST_HISTORY_QOS,
    KEEP_ALL_HISTORY_QOS
  };

  typedef HistoryQosPolicyKind &HistoryQosPolicyKind_out;

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_HistoryQosPolicyKind;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct HistoryQosPolicy;

  typedef
    ::TAO_Fixed_Var_T<
        HistoryQosPolicy
      >
    HistoryQosPolicy_var;

  typedef
    HistoryQosPolicy &
    HistoryQosPolicy_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  HistoryQosPolicy
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef HistoryQosPolicy_var _var_type;
    typedef HistoryQosPolicy_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::HistoryQosPolicyKind kind;
    ::CORBA::Long depth;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_HistoryQosPolicy;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct ResourceLimitsQosPolicy;

  typedef
    ::TAO_Fixed_Var_T<
        ResourceLimitsQosPolicy
      >
    ResourceLimitsQosPolicy_var;

  typedef
    ResourceLimitsQosPolicy &
    ResourceLimitsQosPolicy_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  ResourceLimitsQosPolicy
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef ResourceLimitsQosPolicy_var _var_type;
    typedef ResourceLimitsQosPolicy_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::CORBA::Long max_samples;
    ::CORBA::Long max_instances;
    ::CORBA::Long max_samples_per_instance;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_ResourceLimitsQosPolicy;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct DurabilityServiceQosPolicy;

  typedef
    ::TAO_Fixed_Var_T<
        DurabilityServiceQosPolicy
      >
    DurabilityServiceQosPolicy_var;

  typedef
    DurabilityServiceQosPolicy &
    DurabilityServiceQosPolicy_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  DurabilityServiceQosPolicy
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef DurabilityServiceQosPolicy_var _var_type;
    typedef DurabilityServiceQosPolicy_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::Duration_t service_cleanup_delay;
    DDS::HistoryQosPolicyKind history_kind;
    ::CORBA::Long history_depth;
    ::CORBA::Long max_samples;
    ::CORBA::Long max_instances;
    ::CORBA::Long max_samples_per_instance;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_DurabilityServiceQosPolicy;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct ParticipantBuiltinTopicData;

  typedef
    ::TAO_Var_Var_T<
        ParticipantBuiltinTopicData
      >
    ParticipantBuiltinTopicData_var;

  typedef
    ::TAO_Out_T<
        ParticipantBuiltinTopicData
      >
    ParticipantBuiltinTopicData_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  ParticipantBuiltinTopicData
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef ParticipantBuiltinTopicData_var _var_type;
    typedef ParticipantBuiltinTopicData_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::BuiltinTopicKey_t key;
    DDS::UserDataQosPolicy user_data;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_ParticipantBuiltinTopicData;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct TopicBuiltinTopicData;

  typedef
    ::TAO_Var_Var_T<
        TopicBuiltinTopicData
      >
    TopicBuiltinTopicData_var;

  typedef
    ::TAO_Out_T<
        TopicBuiltinTopicData
      >
    TopicBuiltinTopicData_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  TopicBuiltinTopicData
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef TopicBuiltinTopicData_var _var_type;
    typedef TopicBuiltinTopicData_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::BuiltinTopicKey_t key;
    ::TAO::String_Manager name;
    ::TAO::String_Manager type_name;
    DDS::DurabilityQosPolicy durability;
    DDS::DurabilityServiceQosPolicy durability_service;
    DDS::DeadlineQosPolicy deadline;
    DDS::LatencyBudgetQosPolicy latency_budget;
    DDS::LivelinessQosPolicy liveliness;
    DDS::ReliabilityQosPolicy reliability;
    DDS::TransportPriorityQosPolicy transport_priority;
    DDS::LifespanQosPolicy lifespan;
    DDS::DestinationOrderQosPolicy destination_order;
    DDS::HistoryQosPolicy history;
    DDS::ResourceLimitsQosPolicy resource_limits;
    DDS::OwnershipQosPolicy ownership;
    DDS::TopicDataQosPolicy topic_data;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_TopicBuiltinTopicData;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct PublicationBuiltinTopicData;

  typedef
    ::TAO_Var_Var_T<
        PublicationBuiltinTopicData
      >
    PublicationBuiltinTopicData_var;

  typedef
    ::TAO_Out_T<
        PublicationBuiltinTopicData
      >
    PublicationBuiltinTopicData_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  PublicationBuiltinTopicData
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef PublicationBuiltinTopicData_var _var_type;
    typedef PublicationBuiltinTopicData_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::BuiltinTopicKey_t key;
    DDS::BuiltinTopicKey_t participant_key;
    ::TAO::String_Manager topic_name;
    ::TAO::String_Manager type_name;
    DDS::DurabilityQosPolicy durability;
    DDS::DeadlineQosPolicy deadline;
    DDS::LatencyBudgetQosPolicy latency_budget;
    DDS::LivelinessQosPolicy liveliness;
    DDS::ReliabilityQosPolicy reliability;
    DDS::LifespanQosPolicy lifespan;
    DDS::DestinationOrderQosPolicy destination_order;
    DDS::UserDataQosPolicy user_data;
    DDS::OwnershipQosPolicy ownership;
    DDS::OwnershipStrengthQosPolicy ownership_strength;
    DDS::PresentationQosPolicy presentation;
    DDS::PartitionQosPolicy partition;
    DDS::TopicDataQosPolicy topic_data;
    DDS::GroupDataQosPolicy group_data;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_PublicationBuiltinTopicData;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct SubscriptionBuiltinTopicData;

  typedef
    ::TAO_Var_Var_T<
        SubscriptionBuiltinTopicData
      >
    SubscriptionBuiltinTopicData_var;

  typedef
    ::TAO_Out_T<
        SubscriptionBuiltinTopicData
      >
    SubscriptionBuiltinTopicData_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  SubscriptionBuiltinTopicData
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SubscriptionBuiltinTopicData_var _var_type;
    typedef SubscriptionBuiltinTopicData_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::BuiltinTopicKey_t key;
    DDS::BuiltinTopicKey_t participant_key;
    ::TAO::String_Manager topic_name;
    ::TAO::String_Manager type_name;
    DDS::DurabilityQosPolicy durability;
    DDS::DeadlineQosPolicy deadline;
    DDS::LatencyBudgetQosPolicy latency_budget;
    DDS::LivelinessQosPolicy liveliness;
    DDS::ReliabilityQosPolicy reliability;
    DDS::OwnershipQosPolicy ownership;
    DDS::DestinationOrderQosPolicy destination_order;
    DDS::UserDataQosPolicy user_data;
    DDS::TimeBasedFilterQosPolicy time_based_filter;
    DDS::PresentationQosPolicy presentation;
    DDS::PartitionQosPolicy partition;
    DDS::TopicDataQosPolicy topic_data;
    DDS::GroupDataQosPolicy group_data;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_SubscriptionBuiltinTopicData;

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module DDS

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:679

  template<>
  class Arg_Traits< ::DDS::octSeq>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::octSeq,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  template<>
  class Arg_Traits< ::DDS::BuiltinTopicKey_t_tag>
    : public
        Fixed_Array_Arg_Traits_T<
            ::DDS::BuiltinTopicKey_t_var,
            ::DDS::BuiltinTopicKey_t_forany,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:679

  template<>
  class Arg_Traits< ::DDS::StringSeq>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::StringSeq,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::Duration_t>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::Duration_t,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::UserDataQosPolicy>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::UserDataQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::TopicDataQosPolicy>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::TopicDataQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::GroupDataQosPolicy>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::GroupDataQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::TransportPriorityQosPolicy>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::TransportPriorityQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::LifespanQosPolicy>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::LifespanQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:898

  template<>
  class Arg_Traits< ::DDS::DurabilityQosPolicyKind>
    : public
        Basic_Arg_Traits_T<
            ::DDS::DurabilityQosPolicyKind,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::DurabilityQosPolicy>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::DurabilityQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:898

  template<>
  class Arg_Traits< ::DDS::PresentationQosPolicyAccessScopeKind>
    : public
        Basic_Arg_Traits_T<
            ::DDS::PresentationQosPolicyAccessScopeKind,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::PresentationQosPolicy>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::PresentationQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::DeadlineQosPolicy>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::DeadlineQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::LatencyBudgetQosPolicy>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::LatencyBudgetQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:898

  template<>
  class Arg_Traits< ::DDS::OwnershipQosPolicyKind>
    : public
        Basic_Arg_Traits_T<
            ::DDS::OwnershipQosPolicyKind,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::OwnershipQosPolicy>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::OwnershipQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::OwnershipStrengthQosPolicy>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::OwnershipStrengthQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:898

  template<>
  class Arg_Traits< ::DDS::LivelinessQosPolicyKind>
    : public
        Basic_Arg_Traits_T<
            ::DDS::LivelinessQosPolicyKind,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::LivelinessQosPolicy>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::LivelinessQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::TimeBasedFilterQosPolicy>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::TimeBasedFilterQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::PartitionQosPolicy>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::PartitionQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:898

  template<>
  class Arg_Traits< ::DDS::ReliabilityQosPolicyKind>
    : public
        Basic_Arg_Traits_T<
            ::DDS::ReliabilityQosPolicyKind,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::ReliabilityQosPolicy>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::ReliabilityQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:898

  template<>
  class Arg_Traits< ::DDS::DestinationOrderQosPolicyKind>
    : public
        Basic_Arg_Traits_T<
            ::DDS::DestinationOrderQosPolicyKind,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::DestinationOrderQosPolicy>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::DestinationOrderQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:898

  template<>
  class Arg_Traits< ::DDS::HistoryQosPolicyKind>
    : public
        Basic_Arg_Traits_T<
            ::DDS::HistoryQosPolicyKind,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::HistoryQosPolicy>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::HistoryQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::ResourceLimitsQosPolicy>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::ResourceLimitsQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::DurabilityServiceQosPolicy>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::DurabilityServiceQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::ParticipantBuiltinTopicData>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::ParticipantBuiltinTopicData,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::TopicBuiltinTopicData>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::TopicBuiltinTopicData,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::PublicationBuiltinTopicData>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::PublicationBuiltinTopicData,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::SubscriptionBuiltinTopicData>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::SubscriptionBuiltinTopicData,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
  template<>
  struct  Array_Traits<
      DDS::BuiltinTopicKey_t_forany
    >
  {
    static void free (
        DDS::BuiltinTopicKey_t_slice * _tao_slice);
    static DDS::BuiltinTopicKey_t_slice * dup (
        const DDS::BuiltinTopicKey_t_slice * _tao_slice);
    static void copy (
        DDS::BuiltinTopicKey_t_slice * _tao_to,
        const DDS::BuiltinTopicKey_t_slice * _tao_from);
    static DDS::BuiltinTopicKey_t_slice * alloc (void);
    static void zero (
        DDS::BuiltinTopicKey_t_slice * _tao_slice);
  };
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= ( ::CORBA::Any &, const ::DDS::octSeq &); // copying version
   void operator<<= ( ::CORBA::Any &, ::DDS::octSeq*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::octSeq *&); // deprecated
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::octSeq *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= ( ::CORBA::Any &, const DDS::octSeq &); // copying version
 void operator<<= ( ::CORBA::Any &, DDS::octSeq*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::octSeq *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::octSeq *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_array/any_op_ch.cpp:40


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::BuiltinTopicKey_t_forany &);
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::BuiltinTopicKey_t_forany &);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= ( ::CORBA::Any &, const ::DDS::StringSeq &); // copying version
   void operator<<= ( ::CORBA::Any &, ::DDS::StringSeq*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::StringSeq *&); // deprecated
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::StringSeq *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= ( ::CORBA::Any &, const DDS::StringSeq &); // copying version
 void operator<<= ( ::CORBA::Any &, DDS::StringSeq*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::StringSeq *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::StringSeq *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::Duration_t &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::Duration_t*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::Duration_t *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::Duration_t *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::Duration_t &); // copying version
 void operator<<= (::CORBA::Any &, DDS::Duration_t*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::Duration_t *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::Duration_t *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::UserDataQosPolicy &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::UserDataQosPolicy*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::UserDataQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::UserDataQosPolicy *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::UserDataQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::UserDataQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::UserDataQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::UserDataQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::TopicDataQosPolicy &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::TopicDataQosPolicy*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::TopicDataQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::TopicDataQosPolicy *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::TopicDataQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::TopicDataQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::TopicDataQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::TopicDataQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::GroupDataQosPolicy &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::GroupDataQosPolicy*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::GroupDataQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::GroupDataQosPolicy *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::GroupDataQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::GroupDataQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::GroupDataQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::GroupDataQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::TransportPriorityQosPolicy &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::TransportPriorityQosPolicy*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::TransportPriorityQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::TransportPriorityQosPolicy *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::TransportPriorityQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::TransportPriorityQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::TransportPriorityQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::TransportPriorityQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::LifespanQosPolicy &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::LifespanQosPolicy*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::LifespanQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::LifespanQosPolicy *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::LifespanQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::LifespanQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::LifespanQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::LifespanQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_enum/any_op_ch.cpp:39

#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
  

   void operator<<= (::CORBA::Any &, ::DDS::DurabilityQosPolicyKind);
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::DurabilityQosPolicyKind &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 void operator<<= (::CORBA::Any &, DDS::DurabilityQosPolicyKind);
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::DurabilityQosPolicyKind &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::DurabilityQosPolicy &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::DurabilityQosPolicy*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::DurabilityQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::DurabilityQosPolicy *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::DurabilityQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::DurabilityQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::DurabilityQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::DurabilityQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_enum/any_op_ch.cpp:39

#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
  

   void operator<<= (::CORBA::Any &, ::DDS::PresentationQosPolicyAccessScopeKind);
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::PresentationQosPolicyAccessScopeKind &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 void operator<<= (::CORBA::Any &, DDS::PresentationQosPolicyAccessScopeKind);
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::PresentationQosPolicyAccessScopeKind &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::PresentationQosPolicy &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::PresentationQosPolicy*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::PresentationQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::PresentationQosPolicy *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::PresentationQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::PresentationQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::PresentationQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::PresentationQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::DeadlineQosPolicy &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::DeadlineQosPolicy*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::DeadlineQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::DeadlineQosPolicy *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::DeadlineQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::DeadlineQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::DeadlineQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::DeadlineQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::LatencyBudgetQosPolicy &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::LatencyBudgetQosPolicy*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::LatencyBudgetQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::LatencyBudgetQosPolicy *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::LatencyBudgetQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::LatencyBudgetQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::LatencyBudgetQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::LatencyBudgetQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_enum/any_op_ch.cpp:39

#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
  

   void operator<<= (::CORBA::Any &, ::DDS::OwnershipQosPolicyKind);
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::OwnershipQosPolicyKind &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 void operator<<= (::CORBA::Any &, DDS::OwnershipQosPolicyKind);
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::OwnershipQosPolicyKind &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::OwnershipQosPolicy &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::OwnershipQosPolicy*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::OwnershipQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::OwnershipQosPolicy *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::OwnershipQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::OwnershipQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::OwnershipQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::OwnershipQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::OwnershipStrengthQosPolicy &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::OwnershipStrengthQosPolicy*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::OwnershipStrengthQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::OwnershipStrengthQosPolicy *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::OwnershipStrengthQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::OwnershipStrengthQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::OwnershipStrengthQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::OwnershipStrengthQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_enum/any_op_ch.cpp:39

#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
  

   void operator<<= (::CORBA::Any &, ::DDS::LivelinessQosPolicyKind);
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::LivelinessQosPolicyKind &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 void operator<<= (::CORBA::Any &, DDS::LivelinessQosPolicyKind);
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::LivelinessQosPolicyKind &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::LivelinessQosPolicy &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::LivelinessQosPolicy*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::LivelinessQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::LivelinessQosPolicy *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::LivelinessQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::LivelinessQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::LivelinessQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::LivelinessQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::TimeBasedFilterQosPolicy &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::TimeBasedFilterQosPolicy*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::TimeBasedFilterQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::TimeBasedFilterQosPolicy *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::TimeBasedFilterQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::TimeBasedFilterQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::TimeBasedFilterQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::TimeBasedFilterQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::PartitionQosPolicy &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::PartitionQosPolicy*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::PartitionQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::PartitionQosPolicy *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::PartitionQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::PartitionQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::PartitionQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::PartitionQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_enum/any_op_ch.cpp:39

#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
  

   void operator<<= (::CORBA::Any &, ::DDS::ReliabilityQosPolicyKind);
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::ReliabilityQosPolicyKind &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 void operator<<= (::CORBA::Any &, DDS::ReliabilityQosPolicyKind);
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::ReliabilityQosPolicyKind &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::ReliabilityQosPolicy &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::ReliabilityQosPolicy*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::ReliabilityQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::ReliabilityQosPolicy *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::ReliabilityQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::ReliabilityQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::ReliabilityQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::ReliabilityQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_enum/any_op_ch.cpp:39

#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
  

   void operator<<= (::CORBA::Any &, ::DDS::DestinationOrderQosPolicyKind);
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::DestinationOrderQosPolicyKind &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 void operator<<= (::CORBA::Any &, DDS::DestinationOrderQosPolicyKind);
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::DestinationOrderQosPolicyKind &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::DestinationOrderQosPolicy &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::DestinationOrderQosPolicy*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::DestinationOrderQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::DestinationOrderQosPolicy *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::DestinationOrderQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::DestinationOrderQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::DestinationOrderQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::DestinationOrderQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_enum/any_op_ch.cpp:39

#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
  

   void operator<<= (::CORBA::Any &, ::DDS::HistoryQosPolicyKind);
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::HistoryQosPolicyKind &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 void operator<<= (::CORBA::Any &, DDS::HistoryQosPolicyKind);
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::HistoryQosPolicyKind &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::HistoryQosPolicy &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::HistoryQosPolicy*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::HistoryQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::HistoryQosPolicy *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::HistoryQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::HistoryQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::HistoryQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::HistoryQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::ResourceLimitsQosPolicy &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::ResourceLimitsQosPolicy*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::ResourceLimitsQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::ResourceLimitsQosPolicy *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::ResourceLimitsQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::ResourceLimitsQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::ResourceLimitsQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::ResourceLimitsQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::DurabilityServiceQosPolicy &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::DurabilityServiceQosPolicy*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::DurabilityServiceQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::DurabilityServiceQosPolicy *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::DurabilityServiceQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::DurabilityServiceQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::DurabilityServiceQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::DurabilityServiceQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::ParticipantBuiltinTopicData &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::ParticipantBuiltinTopicData*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::ParticipantBuiltinTopicData *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::ParticipantBuiltinTopicData *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::ParticipantBuiltinTopicData &); // copying version
 void operator<<= (::CORBA::Any &, DDS::ParticipantBuiltinTopicData*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::ParticipantBuiltinTopicData *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::ParticipantBuiltinTopicData *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::TopicBuiltinTopicData &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::TopicBuiltinTopicData*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::TopicBuiltinTopicData *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::TopicBuiltinTopicData *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::TopicBuiltinTopicData &); // copying version
 void operator<<= (::CORBA::Any &, DDS::TopicBuiltinTopicData*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::TopicBuiltinTopicData *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::TopicBuiltinTopicData *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::PublicationBuiltinTopicData &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::PublicationBuiltinTopicData*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::PublicationBuiltinTopicData *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::PublicationBuiltinTopicData *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::PublicationBuiltinTopicData &); // copying version
 void operator<<= (::CORBA::Any &, DDS::PublicationBuiltinTopicData*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::PublicationBuiltinTopicData *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::PublicationBuiltinTopicData *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::SubscriptionBuiltinTopicData &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::SubscriptionBuiltinTopicData*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::SubscriptionBuiltinTopicData *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::SubscriptionBuiltinTopicData *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::SubscriptionBuiltinTopicData &); // copying version
 void operator<<= (::CORBA::Any &, DDS::SubscriptionBuiltinTopicData*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::SubscriptionBuiltinTopicData *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::SubscriptionBuiltinTopicData *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:63

#if !defined _TAO_CDR_OP_DDS_octSeq_H_
#define _TAO_CDR_OP_DDS_octSeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const DDS::octSeq &_tao_sequence);
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    DDS::octSeq &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_DDS_octSeq_H_ */

// TAO_IDL - Generated from
// be/be_visitor_array/cdr_op_ch.cpp:102


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 CORBA::Boolean operator<< (TAO_OutputCDR &strm, const DDS::BuiltinTopicKey_t_forany &_tao_array);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::BuiltinTopicKey_t_forany &_tao_array);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:63

#if !defined _TAO_CDR_OP_DDS_StringSeq_H_
#define _TAO_CDR_OP_DDS_StringSeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const DDS::StringSeq &_tao_sequence);
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    DDS::StringSeq &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_DDS_StringSeq_H_ */

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::Duration_t &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::Duration_t &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::UserDataQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::UserDataQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::TopicDataQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::TopicDataQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::GroupDataQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::GroupDataQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::TransportPriorityQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::TransportPriorityQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::LifespanQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::LifespanQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_enum/cdr_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, DDS::DurabilityQosPolicyKind _tao_enumerator);
 ::CORBA::Boolean operator>> (TAO_InputCDR &strm, DDS::DurabilityQosPolicyKind &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::DurabilityQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::DurabilityQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_enum/cdr_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, DDS::PresentationQosPolicyAccessScopeKind _tao_enumerator);
 ::CORBA::Boolean operator>> (TAO_InputCDR &strm, DDS::PresentationQosPolicyAccessScopeKind &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::PresentationQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::PresentationQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::DeadlineQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::DeadlineQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::LatencyBudgetQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::LatencyBudgetQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_enum/cdr_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, DDS::OwnershipQosPolicyKind _tao_enumerator);
 ::CORBA::Boolean operator>> (TAO_InputCDR &strm, DDS::OwnershipQosPolicyKind &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::OwnershipQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::OwnershipQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::OwnershipStrengthQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::OwnershipStrengthQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_enum/cdr_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, DDS::LivelinessQosPolicyKind _tao_enumerator);
 ::CORBA::Boolean operator>> (TAO_InputCDR &strm, DDS::LivelinessQosPolicyKind &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::LivelinessQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::LivelinessQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::TimeBasedFilterQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::TimeBasedFilterQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::PartitionQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::PartitionQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_enum/cdr_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, DDS::ReliabilityQosPolicyKind _tao_enumerator);
 ::CORBA::Boolean operator>> (TAO_InputCDR &strm, DDS::ReliabilityQosPolicyKind &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::ReliabilityQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::ReliabilityQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_enum/cdr_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, DDS::DestinationOrderQosPolicyKind _tao_enumerator);
 ::CORBA::Boolean operator>> (TAO_InputCDR &strm, DDS::DestinationOrderQosPolicyKind &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::DestinationOrderQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::DestinationOrderQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_enum/cdr_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, DDS::HistoryQosPolicyKind _tao_enumerator);
 ::CORBA::Boolean operator>> (TAO_InputCDR &strm, DDS::HistoryQosPolicyKind &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::HistoryQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::HistoryQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::ResourceLimitsQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::ResourceLimitsQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::DurabilityServiceQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::DurabilityServiceQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::ParticipantBuiltinTopicData &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::ParticipantBuiltinTopicData &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::TopicBuiltinTopicData &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::TopicBuiltinTopicData &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::PublicationBuiltinTopicData &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::PublicationBuiltinTopicData &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::SubscriptionBuiltinTopicData &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::SubscriptionBuiltinTopicData &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "dds_builtinTopicsC.inl"
#endif /* defined INLINE */

#endif /* ifndef */

