#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------
JAVAC         = $(SPLICE_JAVAC)
JAR           = jar
JAVACFLAGS    = $(GENFLAGS)
CLASSEXT      = .class
CLASSDIR      = classes/
OUTPUT_OPTION = -d $(CLASSDIR)
COMPILE.java  = $(JAVAC) $(JAVACFLAGS) -cp $(JAVACCPATH) 
JAVACCPATH    = "$(SPLICE_EXTRA_CP):$(CLASSDIR):../../../../jar/dcpssaj5.jar:"
MAKEFILE      = Makefile.saj5_contentfilteredtopic_types
DEPENDENCIES  = $(MAKEFILE)
LTARGETDIR    = ./
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
GENFLAGS      =  
CLASSES       =  $(CLASSDIR)StockMarket/*$(CLASSEXT) $(CLASSDIR)ContentFilteredTopicDataSubscriber$(CLASSEXT) $(CLASSDIR)ContentFilteredTopicDataPublisher$(CLASSEXT)
JARCLASSES    =  StockMarket/*$(CLASSEXT) ContentFilteredTopicDataSubscriber$(CLASSEXT) ContentFilteredTopicDataPublisher$(CLASSEXT)
JAREXT        = .jar
MAINCLASS     = ContentFilteredTopicDataSubscriber
JARFILE       = $(LTARGETDIR)$(LIBPREFIX)saj5_contentfilteredtopic_types$(LIBSUFFIX)$(JAREXT)
MANIFEST      = saj5_contentfilteredtopic_types.manifest
JARFLAGS      = cvfm
SRC           = StockMarket/*.java ContentFilteredTopicDataSubscriber.java ContentFilteredTopicDataPublisher.java

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(JARFILE)

$(JARFILE): $(CLASSES) $(CLASSDIR)$(MANIFEST)
	@$(TESTDIRSTART) "$(LTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(LTARGETDIR)"
	cd $(CLASSDIR) && $(JAR) $(JARFLAGS) $(JARFILE) $(MANIFEST) $(JARCLASSES) 
	$(MV) $(CLASSDIR)/$(JARFILE) .

$(CLASSDIR)$(MANIFEST):
	echo Class-Path: ../../../../jar/dcpssaj5.jar > $(CLASSDIR)$(MANIFEST)
	echo Main-Class: $(MAINCLASS) >> $(CLASSDIR)$(MANIFEST)

GENERATED_DIRTY = StockMarket

StockMarket: ../idl/ContentFilteredTopicData.idl
	"../../../../bin/idlpp" -I "../../../../etc/idl" -l java ../idl/ContentFilteredTopicData.idl

.PRECIOUS: $(GENERATED_DIRTY)
$(CLASSES): $(GENERATED_DIRTY)

generated: $(GENERATED_DIRTY)
	@-:

$(CLASSDIR)StockMarket/*$(CLASSEXT): StockMarket
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) StockMarket/*.java

$(CLASSDIR)ContentFilteredTopicDataSubscriber$(CLASSEXT): ContentFilteredTopicDataSubscriber.java
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) ContentFilteredTopicDataSubscriber.java

$(CLASSDIR)ContentFilteredTopicDataPublisher$(CLASSEXT): ContentFilteredTopicDataPublisher.java
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) ContentFilteredTopicDataPublisher.java

clean:
	-$(RM) $(CLASSES)

realclean: clean
	-$(RM) $(BIN)
	-$(RM) $(GENERATED_DIRTY)
	-$(RM) $(CLASSDIR)$(MANIFEST)

check-syntax:
	$(COMPILE.java) $(EXPORTFLAGS) $(CHK_SOURCES)

