#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------
JAVAC         = $(SPLICE_JAVAC)
JAR           = jar
JAVACFLAGS    = $(GENFLAGS)
CLASSEXT      = .class
CLASSDIR      = classes/
OUTPUT_OPTION = -d $(CLASSDIR)
COMPILE.java  = $(JAVAC) $(JAVACFLAGS) -cp $(JAVACCPATH) 
JAVACCPATH    = "$(SPLICE_EXTRA_CP):$(CLASSDIR):../../../../jar/dcpssaj5.jar:"
MAKEFILE      = Makefile.Saj5_Throughput_Types
DEPENDENCIES  = $(MAKEFILE)
LTARGETDIR    = ./
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
GENFLAGS      =  
CLASSES       =  $(CLASSDIR)./ThroughputModule/*$(CLASSEXT) $(CLASSDIR)Subscriber_impl$(CLASSEXT) $(CLASSDIR)SubEntities$(CLASSEXT) $(CLASSDIR)PubEntities$(CLASSEXT) $(CLASSDIR)subscriber$(CLASSEXT) $(CLASSDIR)publisher$(CLASSEXT) $(CLASSDIR)ExampleUtilities$(CLASSEXT) $(CLASSDIR)Publisher_impl$(CLASSEXT)
JARCLASSES    =  ./ThroughputModule/*$(CLASSEXT) Subscriber_impl$(CLASSEXT) SubEntities$(CLASSEXT) PubEntities$(CLASSEXT) subscriber$(CLASSEXT) publisher$(CLASSEXT) ExampleUtilities$(CLASSEXT) Publisher_impl$(CLASSEXT)
JAREXT        = .jar
MAINCLASS     = subscriber
JARFILE       = $(LTARGETDIR)$(LIBPREFIX)Saj5_Throughput_Types$(LIBSUFFIX)$(JAREXT)
MANIFEST      = Saj5_Throughput_Types.manifest
JARFLAGS      = cvfm
SRC           = ./ThroughputModule/*.java Subscriber_impl.java SubEntities.java PubEntities.java subscriber.java publisher.java ExampleUtilities.java Publisher_impl.java

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(JARFILE)

$(JARFILE): $(CLASSES) $(CLASSDIR)$(MANIFEST)
	@$(TESTDIRSTART) "$(LTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(LTARGETDIR)"
	cd $(CLASSDIR) && $(JAR) $(JARFLAGS) $(JARFILE) $(MANIFEST) $(JARCLASSES) 
	$(MV) $(CLASSDIR)/$(JARFILE) .

$(CLASSDIR)$(MANIFEST):
	echo Class-Path: ../../../../jar/dcpssaj5.jar > $(CLASSDIR)$(MANIFEST)
	echo Main-Class: $(MAINCLASS) >> $(CLASSDIR)$(MANIFEST)

GENERATED_DIRTY = ./ThroughputModule

./ThroughputModule: ../idl/Throughput.idl
	"../../../../bin/idlpp" -I "../../../../etc/idl" -l java ../idl/Throughput.idl

.PRECIOUS: $(GENERATED_DIRTY)
$(CLASSES): $(GENERATED_DIRTY)

generated: $(GENERATED_DIRTY)
	@-:

$(CLASSDIR)./ThroughputModule/*$(CLASSEXT): ./ThroughputModule
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) ./ThroughputModule/*.java

$(CLASSDIR)Subscriber_impl$(CLASSEXT): Subscriber_impl.java
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) Subscriber_impl.java

$(CLASSDIR)SubEntities$(CLASSEXT): SubEntities.java
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) SubEntities.java

$(CLASSDIR)PubEntities$(CLASSEXT): PubEntities.java
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) PubEntities.java

$(CLASSDIR)subscriber$(CLASSEXT): subscriber.java
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) subscriber.java

$(CLASSDIR)publisher$(CLASSEXT): publisher.java
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) publisher.java

$(CLASSDIR)ExampleUtilities$(CLASSEXT): ExampleUtilities.java
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) ExampleUtilities.java

$(CLASSDIR)Publisher_impl$(CLASSEXT): Publisher_impl.java
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) Publisher_impl.java

clean:
	-$(RM) $(CLASSES)

realclean: clean
	-$(RM) $(BIN)
	-$(RM) $(GENERATED_DIRTY)
	-$(RM) $(CLASSDIR)$(MANIFEST)

check-syntax:
	$(COMPILE.java) $(EXPORTFLAGS) $(CHK_SOURCES)

