#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------
JAVAC         = $(SPLICE_JAVAC)
JAR           = jar
JAVACFLAGS    = $(GENFLAGS)
CLASSEXT      = .class
CLASSDIR      = classes/
OUTPUT_OPTION = -d $(CLASSDIR)
COMPILE.java  = $(JAVAC) $(JAVACFLAGS) -cp $(JAVACCPATH) 
JAVACCPATH    = "$(SPLICE_EXTRA_CP):Saj5_Throughput_Types.jar:$(CLASSDIR):../../../../jar/dcpssaj5.jar:"
MAKEFILE      = Makefile.Saj5_Throughput_Subscriber
DEPENDENCIES  = $(MAKEFILE)
LTARGETDIR    = ./
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
GENFLAGS      =  
CLASSES       =  $(CLASSDIR)subscriber$(CLASSEXT) $(CLASSDIR)Subscriber_impl$(CLASSEXT) $(CLASSDIR)SubEntities$(CLASSEXT) $(CLASSDIR)ExampleUtilities$(CLASSEXT)
JARCLASSES    =  subscriber$(CLASSEXT) Subscriber_impl$(CLASSEXT) SubEntities$(CLASSEXT) ExampleUtilities$(CLASSEXT)
JAREXT        = .jar
MAINCLASS     = subscriber
JARFILE       = $(LTARGETDIR)$(LIBPREFIX)Saj5_Throughput_Subscriber$(LIBSUFFIX)$(JAREXT)
MANIFEST      = Saj5_Throughput_Subscriber.manifest
JARFLAGS      = cvfm
SRC           = subscriber.java Subscriber_impl.java SubEntities.java ExampleUtilities.java
CLASSES       += classes/Subscriber_impl*.class
JARCLASSES    += Subscriber_impl*.class
JARCLASSES    += ExampleUtilities*.class


#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(JARFILE)

$(JARFILE): $(CLASSES) $(CLASSDIR)$(MANIFEST)
	@$(TESTDIRSTART) "$(LTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(LTARGETDIR)"
	cd $(CLASSDIR) && $(JAR) $(JARFLAGS) $(JARFILE) $(MANIFEST) $(JARCLASSES) 
	$(MV) $(CLASSDIR)/$(JARFILE) .

$(CLASSDIR)$(MANIFEST):
	echo Class-Path: Saj5_Throughput_Types.jar ../../../../jar/dcpssaj5.jar > $(CLASSDIR)$(MANIFEST)
	echo Main-Class: $(MAINCLASS) >> $(CLASSDIR)$(MANIFEST)

generated: $(GENERATED_DIRTY)
	@-:

$(CLASSDIR)subscriber$(CLASSEXT): subscriber.java
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) subscriber.java

$(CLASSDIR)Subscriber_impl$(CLASSEXT): Subscriber_impl.java
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) Subscriber_impl.java

$(CLASSDIR)SubEntities$(CLASSEXT): SubEntities.java
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) SubEntities.java

$(CLASSDIR)ExampleUtilities$(CLASSEXT): ExampleUtilities.java
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) ExampleUtilities.java

clean:
	-$(RM) $(CLASSES)

realclean: clean
	-$(RM) $(BIN)
	-$(RM) $(CLASSDIR)$(MANIFEST)

check-syntax:
	$(COMPILE.java) $(EXPORTFLAGS) $(CHK_SOURCES)

