# -*-Makefile-*-
#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------

CC            = gcc
CXX           = g++
LD            = $(CXX) $(CCFLAGS) $(PICFLAGS) $(GENFLAGS)
AR            = ar
PICFLAGS      = -fPIC
CPPFLAGS      = $(PICFLAGS) $(GENFLAGS) -D_REENTRANT -Wall -I"$(ACE_ROOT)" -I"$(TAO_ROOT)" -I"$(TAO_ROOT)/include" -I"$(ACE_ROOT)/include" -I"../../../../../include" -I"../../../../../include/sys" -I"../../../../../include/dcps/C++/CCPP" -I"../../../../../include/dcps/C++/CCPP/DDS_OpenFusion_2" -I"." -I"../../../../../examples/include" -I"../../../../../examples"
OBJEXT        = .o
OUTPUT_OPTION = -o "$@"
COMPILE.c     = $(CC) $(CFLAGS) $(CPPFLAGS) -c
COMPILE.cc    = $(CXX) $(CCFLAGS) $(CPPFLAGS) -c
LDFLAGS       = -L"." -L"$(ACE_ROOT)/lib" -L"$(TAO_ROOT)/lib" -L"../../../../../lib" -Wl,-rpath,\$$ORIGIN -Wl,-rpath,\$$ORIGIN/../../../../../lib
CCC           = $(CXX)
MAKEFILE      = Makefile.ccpp_helloworld_types
DEPENDENCIES  = $(MAKEFILE)
LTARGETDIR    = ./
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
EXEEXT        = 
LIBPREFIX     = lib
LIBSUFFIX     = 
GENFLAGS      = -O3 -DNDEBUG
LDLIBS        = -l"TAO_PortableServer$(LIBSUFFIX)" -l"TAO_AnyTypeCode$(LIBSUFFIX)" -l"TAO$(LIBSUFFIX)" -l"ACE$(LIBSUFFIX)" -l"dcpsccpp" -l"ddskernel" -ldl $(subst lib,-l,$(sort $(basename $(notdir $(wildcard /usr/lib/librt.so /lib/librt.so))))) -lpthread
OBJS          = .obj$(CFG)/HelloWorldDataSplDcps$(OBJEXT) .obj$(CFG)/HelloWorldDataDcps_impl$(OBJEXT) .obj$(CFG)/HelloWorldDataDcpsC$(OBJEXT) .obj$(CFG)/HelloWorldDataDcpsS$(OBJEXT) .obj$(CFG)/HelloWorldDataC$(OBJEXT) .obj$(CFG)/HelloWorldDataS$(OBJEXT)
AREXT         = .a
LIB           = $(LTARGETDIR)$(LIBPREFIX)ccpp_helloworld_types$(LIBSUFFIX)$(AREXT)
SOEXT         = .so
SHTARGETDIR   = ./
SHLIB         = $(SHTARGETDIR)$(LIBPREFIX)ccpp_helloworld_types$(LIBSUFFIX)$(SOEXT)
SHFLAGS       = -shared
SRC           = HelloWorldDataSplDcps.cpp HelloWorldDataDcps_impl.cpp HelloWorldDataDcpsC.cpp HelloWorldDataDcpsS.cpp HelloWorldDataC.cpp HelloWorldDataS.cpp
LINK.cc       = $(LD) $(LDFLAGS)
DYNAMICFLAGS  = -DOSPL_BUILDEXAMPLE_LIB
STATICFLAGS   = -DACE_AS_STATIC_LIBS -DTAO_AS_STATIC_LIBS
EXPORTFLAGS   = $(DYNAMICFLAGS)

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(SHLIB)

$(SHLIB): $(OBJS)
	@$(TESTDIRSTART) "$(SHTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(SHTARGETDIR)"
	$(LINK.cc) $(SHFLAGS) $(OBJS) $(LDLIBS) $(OUTPUT_OPTION)

$(LIB): $(OBJS)
	@$(TESTDIRSTART) "$(LTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(LTARGETDIR)"
	$(AR) $(ARFLAGS) $(LIB) $(OBJS) 

GENERATED_DIRTY = HelloWorldDataDcpsC.inl HelloWorldDataDcpsC.h HelloWorldDataDcpsS.h HelloWorldDataDcpsC.cpp HelloWorldDataDcpsS.cpp ./HelloWorldDataC.inl ./HelloWorldDataC.h ./HelloWorldDataS.h ./HelloWorldDataC.cpp ./HelloWorldDataS.cpp ./HelloWorldDataDcps.idl ./ccpp_HelloWorldData.h ./HelloWorldDataSplDcps.cpp ./HelloWorldDataDcps_impl.cpp ./HelloWorldDataDcps_impl.h ./HelloWorldDataSplDcps.h


export DYLD_LIBRARY_PATH := $(DYLD_LIBRARY_PATH):$(ACE_ROOT)/lib
export LD_LIBRARY_PATH   := $(LD_LIBRARY_PATH):$(ACE_ROOT)/lib
export SHLIB_PATH        := $(SHLIB_PATH):$(ACE_ROOT)/lib
export LIBPATH           := $(LIBPATH):$(ACE_ROOT)/lib
export PATH              := $(PATH):$(ACE_ROOT)/lib

.NOTPARALLEL:
HelloWorldDataDcpsC.inl HelloWorldDataDcpsC.h HelloWorldDataDcpsS.h HelloWorldDataDcpsC.cpp HelloWorldDataDcpsS.cpp: HelloWorldDataDcps.idl
	$(ACE_ROOT)/bin/tao_idl -Wb,pre_include=ace/pre.h -Wb,post_include=ace/post.h -I$(TAO_ROOT) -I "../../../../../etc/idl" -I ../../idl -Wb,export_macro=OS_EXAMPLE_API -Wb,export_include=../../../../../examples/include/examples_export.h HelloWorldDataDcps.idl


.NOTPARALLEL:
./HelloWorldDataC.inl ./HelloWorldDataC.h ./HelloWorldDataS.h ./HelloWorldDataC.cpp ./HelloWorldDataS.cpp: ../../idl/HelloWorldData.idl
	@$(TESTDIRSTART) "." $(TESTDIREND) $(MKDIR) "."
	$(ACE_ROOT)/bin/tao_idl -Wb,pre_include=ace/pre.h -Wb,post_include=ace/post.h -I$(TAO_ROOT) -I "../../../../../etc/idl" -I ../../idl -Wb,export_macro=OS_EXAMPLE_API -Wb,export_include=../../../../../examples/include/examples_export.h ../../idl/HelloWorldData.idl





export DYLD_LIBRARY_PATH := $(DYLD_LIBRARY_PATH):../../../../../bin:../../../../../lib
export LD_LIBRARY_PATH   := $(LD_LIBRARY_PATH):../../../../../bin:../../../../../lib
export SHLIB_PATH        := $(SHLIB_PATH):../../../../../bin:../../../../../lib
export LIBPATH           := $(LIBPATH):../../../../../bin:../../../../../lib
export PATH              := $(PATH):../../../../../bin:../../../../../lib

.NOTPARALLEL:
./HelloWorldDataDcps.idl ./ccpp_HelloWorldData.h ./HelloWorldDataSplDcps.cpp ./HelloWorldDataDcps_impl.cpp ./HelloWorldDataDcps_impl.h ./HelloWorldDataSplDcps.h: ../../idl/HelloWorldData.idl
	@$(TESTDIRSTART) "." $(TESTDIREND) $(MKDIR) "."
	"../../../../../bin/idlpp" -I "../../../../../etc/idl" -C -l cpp -b CCPP/DDS_OpenFusion_2 ../../idl/HelloWorldData.idl

.PRECIOUS: $(GENERATED_DIRTY)
$(OBJS): $(GENERATED_DIRTY)

generated: $(GENERATED_DIRTY)
	@-:

.obj$(CFG)/HelloWorldDataSplDcps$(OBJEXT): HelloWorldDataSplDcps.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) HelloWorldDataSplDcps.cpp

.obj$(CFG)/HelloWorldDataDcps_impl$(OBJEXT): HelloWorldDataDcps_impl.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) HelloWorldDataDcps_impl.cpp

.obj$(CFG)/HelloWorldDataDcpsC$(OBJEXT): HelloWorldDataDcpsC.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) HelloWorldDataDcpsC.cpp

.obj$(CFG)/HelloWorldDataDcpsS$(OBJEXT): HelloWorldDataDcpsS.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) HelloWorldDataDcpsS.cpp

.obj$(CFG)/HelloWorldDataC$(OBJEXT): HelloWorldDataC.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) HelloWorldDataC.cpp

.obj$(CFG)/HelloWorldDataS$(OBJEXT): HelloWorldDataS.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) HelloWorldDataS.cpp

clean:
	-$(RM) $(OBJS)

realclean: clean
	-$(RM) $(SHLIB) $(LIB)
	-$(RM) $(GENERATED_DIRTY)
	-$(RM) .obj$(CFG)/

check-syntax:
	$(COMPILE.cc) $(EXPORTFLAGS) $(CHK_SOURCES)

